server.port=${PORT:8007}
spring.data.mongodb.uri=${MONGO_URL:mongodb://mongodb:27017/orders}
spring.rabbitmq.host=${AMQP_HOST:rabbitmq}
spring.rabbitmq.username=${AMQP_USER:guest}
spring.rabbitmq.password=${AMQP_PASS:guest}
notification.url=${NOTIFICATION_URL:http://notification:8008}
shipping.url=${SHIPPING_URL:http://shipping:8004}
